family:
  # 文件路径 示例（ Windows配置D:/family/uploadPath，Linux配置 /home/family/uploadPath）
  profile: /root/family/files
spring:
  # redis 配置
  redis:
    # 地址
    host: ${REDIS_HOST}
    # 端口，默认为6379
    port: ${REDIS_PORT}
    # 数据库索引
    database: ${REDIS_DATABASE}
    # 密码
    password: ${REDIS_PASSWORD}
  #数据源配置
  datasource:
    druid:
      # 主库数据源
      master:
        url: ${MYSQL_URL}
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
#      statViewServlet:
#        # 控制台管理用户名和密码
#        login-username: family
#        login-password: 123456
logging:
  level:
    com.zlc: warn